### ISSUE TITLE
Some Sections in the Cookies View Do Not Translate Certain Parts

### ISSUE THREAD

**Issue by sbono2016** [whitecube/laravel-cookie-consent#15]
Thank you for the plugin; this is exactly what I was looking for for many weeks.

I encountered a minor issue in the view related to translation.

I had to make some code changes to make it work:"

+- line 37 :
From:
```
<span class="cookies__box">
      <strong class="cookies__label">{{ $category->title }}</strong>
  </span>
  @if($category->description)
      <p class="cookies__info">{{ $category->description }}</p>
  @endif
```

To:
```
<span class="cookies__box">
    <strong class="cookies__label">@lang('cookieConsent::cookies.categories.'.$category->key().'.title')</strong>
</span>
@if($category->description)
    <p class="cookies__info">@lang('cookieConsent::cookies.categories.'.$category->key().'.description')</p>
@endif
```

The same issue also exists with the cookie description, but I haven't found a way to modify it yet...
+- line 48 :
```
<li class="cookies__cookie">
  <p class="cookies__name">{{ $cookie->name }}</p>
  <p class="cookies__duration">{{ \Carbon\CarbonInterval::minutes($cookie->duration)->cascade() }}</p>
  @if($cookie->description)
      <p class="cookies__description">{{ $cookie->description }}</p>
  @endif
</li>
```

**Comment by toonvandenbos** [comment]
Hi @sbono2016,

This is weird. I'm not sure the suggested fix is appropriate since you can add your own categories (which are not necessarily defined inside `cookieConsent::cookies.categories`). Also, I think it would be interesting to know _why_ the default method didn't work in your case so we can figure out whether there is a problem with your project or with the package itself in a specific setup.

Could you elaborate? Thanks!

**Comment by QuentinGab** [comment]
Hi, 
I run into the same situation (mixed locales) and I just want to add some context about translation and the cookie registration process with service provider.

The doc says to register cookies in the boot method of a serviceProvider, but doing that raise a major problem:
The locale is probably not already setup, because the boot method is called before any other code of you app (middleware, controller, ...) it will probably fallback to the default locale causing mixed languages to be rendered in the final result.

I would recommand 2 solutions:
- register cookies in a middleware after all your logic regarding setting le locale. It will work with the actual state of the package.
- update the package to call @lang or __ in the blade view and only passing localization keys when registering cookies.

**Comment by MaartenOste** [comment]
Same issue here. The default language of my app is "nl" and when switching to "en", some translations stay in "nl".
Most translations come through, but the category title and description and the "defaults" seem to be failing (see images).

I've created a CookieServiceprovider and added this provider as the last provider in my config/app.php. 
Registering the cookies in the AppServiceProvider doesn't seem to make a difference.

![Screenshot 2023-11-21 at 14 11 11](https://github.com/whitecube/laravel-cookie-consent/assets/36887472/585122b4-6f41-459a-a33f-06de1d93c09f)
![Screenshot 2023-11-21 at 14 11 04](https://github.com/whitecube/laravel-cookie-consent/assets/36887472/fec623bd-9845-4d2e-8ea1-c9c2a817712b)

**Comment by toonvandenbos** [comment]
What @QuentinGab mentioned is accurate. Defining cookies while booting Laravel is indeed too ealry, that's why I created PR #29 which is providing a publishable `CookiesServiceProvider` responsible for calling the cookies definition at the right moment in Laravel's booting lifecycle.

This will be published as `v1.1.0` soon, please upgrade and read the updated "Usage" section in the docs.

**Comment by petethewizard** [comment]
I am using 1.2 and did everything in the usage section but keep having this problem. Any ideas?

**Comment by petethewizard** [comment]
I am using "codezero/laravel-localized-routes", maybe it has something to do with it?

**Comment by alien-rat** [comment]
I am using 1.2.3 and did everything in the usage section but keep having this problem.

**Comment by toonvandenbos** [comment]
Could you setup a repo where we could reproduce the error? Thanks!

**Comment by petethewizard** [comment]
@toonvandenbos I've setup a repo here: https://github.com/petethewizard/cookie-consent-translation-issue. There is docker compose file ready to go and bit info in the readme.

**Comment by davidoskay** [comment]
Yeah, still it's loaded before middlewares which sets up my languages. I spend a lot of time to fix this. 
Doing `app()->register(CookiesServiceProvider::class);` inside middleware setting locale fixes problem.

**Comment by a-m-zill** [comment]
Hello,

i have still the same issue. I have done all what was under **Usage** in the Readme file.
I have customized the view file `cookies.blade.php` like @sbono2016 has suggested.
But this only the half way, because details about the cookies itself is not able to translate.

Has anyone an further idea or solution?

Thx
