### ISSUE TITLE
Showing the right duration for each cookie

### ISSUE THREAD

**Issue by albertogato** [whitecube/laravel-cookie-consent#56]
In cookies.blade.php the duration of each cookie is printed with the cascade() method:

`<p class="cookies__duration">{{ \Carbon\CarbonInterval::minutes($cookie->duration)->cascade() }}</p>`

For a duration of duration of 2 * 365 * 24 * 60 minutes, I would expect "2 years" returned, but it returns "2 years 2 months 2 days".

This behaviour is caused by the default values of the cascade factors, but setting the values like this:

```
\Carbon\CarbonInterval::setCascadeFactors([
    'minute' => [60, 'seconds'],
    'hour' => [60, 'minutes'],
    'day' => [24, 'hours'],
    'year' => [365, 'days'],
]);
```

it returns the expected value.

Is this something that should be changed in the source of this project, or a setting that should be placed in another place like the boot() method of the class AppServiceProvider?

**Comment by toonvandenbos** [comment]
Hi Alberto,

We covered this issue in the project's README, [under the cookie policy details page](https://github.com/whitecube/laravel-cookie-consent#user-content-cookie-policy-details-page). Since Carbon's default factors are there for a reason, we do not want to create timing errors in applications using this package and therefore it is recommended to set these cascade factors yourself, for instance in a ServiceProvider's boot methos.

Have a great day!

**Comment by albertogato** [comment]
Ok, I completely missed that issue.

Thank you very much!

**Comment by sebastianfeistl** [comment]
Hi, I came across this issue (along with #48) while troubleshooting a similar problem, and I wanted to suggest a potential enhancement.

I implemented an isolated solution in my project that modifies Carbon’s cascade factors only where needed, avoiding global side effects while ensuring the durations are formatted as expected. Here’s the key part of the implementation:

```php
public function getFormattedDuration(): string
{
    $factors = \Carbon\CarbonInterval::getCascadeFactors();
    $factors['years'] = [365, 'dayz'];
    \Carbon\CarbonInterval::setCascadeFactors($factors);

    $formatted = \Carbon\CarbonInterval::minutes($this->duration)->cascade();

    // Reset factors to avoid side effects
    \Carbon\CarbonInterval::setCascadeFactors(\Carbon\CarbonInterval::getDefaultCascadeFactors());

    return $formatted;
}
```

and I'm calling this method directly from `cookies.blade.php`

```html
<p class="cookies__duration">{{ $cookie->getFormattedDuration() }}</p>
```

This approach ensures that durations like (60 * 24 * 365) * 2 correctly display "2 years" instead of "2 years 2 months 2 days", while leaving other parts of the app unaffected.

I understand the reasoning behind not setting cascade factors globally (e.g., in `AppServiceProvider`), but since this method is isolated to the package’s context, it seems like a lightweight and safe way to improve the default behavior.

@toonvandenbos Would you consider a similar enhancement for future versions? Or is there a specific reason this approach was avoided?

Thanks for your time and the great work on this package!
