### ISSUE TITLE
How to get the user's consent history?

### ISSUE THREAD

**Issue by core45** [whitecube/laravel-cookie-consent#67]
The situation:
An user claims that he did not give the consent. 

How can I get the consents history and prove that he did?
Where this package store the consent data?

**Comment by core45** [comment]
helooo?

**Comment by core45** [comment]
anybody? Is it possible? is is not possible.
Does it cost you so much to answer me?

**Comment by toonvandenbos** [comment]
Hi @core45,

It does indeed cost us quite a lot of time to maintain all the (free) open-source packages we offer, sorry for the delay.

Consent is stored on the user's device using a cookie, meaning you could try to fetch some information from the user's next visit, hoping it was not cleared since.

This package does not (and will probably never) store consent history in a database/file/cache/etc. You could however try to hook into the package's methods in order to add your custom behavior. This could be done by registering an extended version of this package's [CookiesManager](https://github.com/whitecube/laravel-cookie-consent/blob/main/src/CookiesManager.php) singleton.

Hope this helps!

**Comment by core45** [comment]
Thank you very much for the answer!
